### ISSUE TITLE
ValueError: could not convert string to float: '172.19.1.46-10.200.7.7-52422-3128-6'

### ISSUE THREAD

**Issue by elybes** [krzysiekniburski/Network-Traffic-Classification#2]
Hello sir, I am working on a project about real time network traffic classification and I was looking for a pre-trained model or a model i can follow and I found your github. I tried to run it and follow step by step to understund everything but i have got this error while running the feature defining code `feats = [x for x in df.columns if x != 'ProtocolName']
X = df[feats].astype(float)
Y = df['ProtocolName']`
the error = `ValueError: could not convert string to float: '172.19.1.46-10.200.7.7-52422-3128-6'`
I hope you help me on it. 
Thank you in advance.

**Comment by krzysiekniburski** [comment]
Hello, please refer to the closed issue: https://github.com/krzysiekniburski/Network-Traffic-Classification/issues/1
It should help you
